/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as PerfilLojistaRouteImport } from './routes/perfil.lojista'
import { Route as LojistaIdRouteImport } from './routes/lojista.$id'
import { Route as DashboardPrestadorRouteImport } from './routes/dashboard.prestador'
import { Route as DashboardLojistaRouteImport } from './routes/dashboard.lojista'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedPrestadorRouteImport } from './routes/_authenticated.prestador'
import { Route as AuthenticatedParceiroRouteImport } from './routes/_authenticated.parceiro'
import { Route as AuthenticatedLojistaRouteImport } from './routes/_authenticated.lojista'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated.feed'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedClienteRouteImport } from './routes/_authenticated.cliente'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated.chat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedFeedIndexRouteImport } from './routes/_authenticated.feed.index'
import { Route as ApiPublicSetupDbRouteImport } from './routes/api/public/setup-db'
import { Route as AuthenticatedFeedPrestadorRouteImport } from './routes/_authenticated.feed.prestador'
import { Route as AuthenticatedFeedParceiroRouteImport } from './routes/_authenticated.feed.parceiro'
import { Route as AuthenticatedFeedLojistaRouteImport } from './routes/_authenticated.feed.lojista'
import { Route as AuthenticatedFeedClienteRouteImport } from './routes/_authenticated.feed.cliente'
import { Route as AuthenticatedChatPeerIdRouteImport } from './routes/_authenticated.chat.$peerId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const PerfilLojistaRoute = PerfilLojistaRouteImport.update({
  id: '/perfil/lojista',
  path: '/perfil/lojista',
  getParentRoute: () => rootRouteImport,
} as any)
const LojistaIdRoute = LojistaIdRouteImport.update({
  id: '/lojista/$id',
  path: '/lojista/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPrestadorRoute = DashboardPrestadorRouteImport.update({
  id: '/dashboard/prestador',
  path: '/dashboard/prestador',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLojistaRoute = DashboardLojistaRouteImport.update({
  id: '/dashboard/lojista',
  path: '/dashboard/lojista',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrestadorRoute = AuthenticatedPrestadorRouteImport.update({
  id: '/prestador',
  path: '/prestador',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParceiroRoute = AuthenticatedParceiroRouteImport.update({
  id: '/parceiro',
  path: '/parceiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLojistaRoute = AuthenticatedLojistaRouteImport.update({
  id: '/lojista',
  path: '/lojista',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClienteRoute = AuthenticatedClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedIndexRoute = AuthenticatedFeedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedFeedRoute,
} as any)
const ApiPublicSetupDbRoute = ApiPublicSetupDbRouteImport.update({
  id: '/api/public/setup-db',
  path: '/api/public/setup-db',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFeedPrestadorRoute =
  AuthenticatedFeedPrestadorRouteImport.update({
    id: '/prestador',
    path: '/prestador',
    getParentRoute: () => AuthenticatedFeedRoute,
  } as any)
const AuthenticatedFeedParceiroRoute =
  AuthenticatedFeedParceiroRouteImport.update({
    id: '/parceiro',
    path: '/parceiro',
    getParentRoute: () => AuthenticatedFeedRoute,
  } as any)
const AuthenticatedFeedLojistaRoute =
  AuthenticatedFeedLojistaRouteImport.update({
    id: '/lojista',
    path: '/lojista',
    getParentRoute: () => AuthenticatedFeedRoute,
  } as any)
const AuthenticatedFeedClienteRoute =
  AuthenticatedFeedClienteRouteImport.update({
    id: '/cliente',
    path: '/cliente',
    getParentRoute: () => AuthenticatedFeedRoute,
  } as any)
const AuthenticatedChatPeerIdRoute = AuthenticatedChatPeerIdRouteImport.update({
  id: '/$peerId',
  path: '/$peerId',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/cliente': typeof AuthenticatedClienteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feed': typeof AuthenticatedFeedRouteWithChildren
  '/lojista': typeof AuthenticatedLojistaRoute
  '/parceiro': typeof AuthenticatedParceiroRoute
  '/prestador': typeof AuthenticatedPrestadorRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/dashboard/lojista': typeof DashboardLojistaRoute
  '/dashboard/prestador': typeof DashboardPrestadorRoute
  '/lojista/$id': typeof LojistaIdRoute
  '/perfil/lojista': typeof PerfilLojistaRoute
  '/auth/': typeof AuthIndexRoute
  '/chat/$peerId': typeof AuthenticatedChatPeerIdRoute
  '/feed/cliente': typeof AuthenticatedFeedClienteRoute
  '/feed/lojista': typeof AuthenticatedFeedLojistaRoute
  '/feed/parceiro': typeof AuthenticatedFeedParceiroRoute
  '/feed/prestador': typeof AuthenticatedFeedPrestadorRoute
  '/api/public/setup-db': typeof ApiPublicSetupDbRoute
  '/feed/': typeof AuthenticatedFeedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/cliente': typeof AuthenticatedClienteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lojista': typeof AuthenticatedLojistaRoute
  '/parceiro': typeof AuthenticatedParceiroRoute
  '/prestador': typeof AuthenticatedPrestadorRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/dashboard/lojista': typeof DashboardLojistaRoute
  '/dashboard/prestador': typeof DashboardPrestadorRoute
  '/lojista/$id': typeof LojistaIdRoute
  '/perfil/lojista': typeof PerfilLojistaRoute
  '/auth': typeof AuthIndexRoute
  '/chat/$peerId': typeof AuthenticatedChatPeerIdRoute
  '/feed/cliente': typeof AuthenticatedFeedClienteRoute
  '/feed/lojista': typeof AuthenticatedFeedLojistaRoute
  '/feed/parceiro': typeof AuthenticatedFeedParceiroRoute
  '/feed/prestador': typeof AuthenticatedFeedPrestadorRoute
  '/api/public/setup-db': typeof ApiPublicSetupDbRoute
  '/feed': typeof AuthenticatedFeedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/cliente': typeof AuthenticatedClienteRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRouteWithChildren
  '/_authenticated/lojista': typeof AuthenticatedLojistaRoute
  '/_authenticated/parceiro': typeof AuthenticatedParceiroRoute
  '/_authenticated/prestador': typeof AuthenticatedPrestadorRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/dashboard/lojista': typeof DashboardLojistaRoute
  '/dashboard/prestador': typeof DashboardPrestadorRoute
  '/lojista/$id': typeof LojistaIdRoute
  '/perfil/lojista': typeof PerfilLojistaRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/chat/$peerId': typeof AuthenticatedChatPeerIdRoute
  '/_authenticated/feed/cliente': typeof AuthenticatedFeedClienteRoute
  '/_authenticated/feed/lojista': typeof AuthenticatedFeedLojistaRoute
  '/_authenticated/feed/parceiro': typeof AuthenticatedFeedParceiroRoute
  '/_authenticated/feed/prestador': typeof AuthenticatedFeedPrestadorRoute
  '/api/public/setup-db': typeof ApiPublicSetupDbRoute
  '/_authenticated/feed/': typeof AuthenticatedFeedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/terms'
    | '/admin'
    | '/chat'
    | '/cliente'
    | '/dashboard'
    | '/feed'
    | '/lojista'
    | '/parceiro'
    | '/prestador'
    | '/profile'
    | '/dashboard/lojista'
    | '/dashboard/prestador'
    | '/lojista/$id'
    | '/perfil/lojista'
    | '/auth/'
    | '/chat/$peerId'
    | '/feed/cliente'
    | '/feed/lojista'
    | '/feed/parceiro'
    | '/feed/prestador'
    | '/api/public/setup-db'
    | '/feed/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/terms'
    | '/admin'
    | '/chat'
    | '/cliente'
    | '/dashboard'
    | '/lojista'
    | '/parceiro'
    | '/prestador'
    | '/profile'
    | '/dashboard/lojista'
    | '/dashboard/prestador'
    | '/lojista/$id'
    | '/perfil/lojista'
    | '/auth'
    | '/chat/$peerId'
    | '/feed/cliente'
    | '/feed/lojista'
    | '/feed/parceiro'
    | '/feed/prestador'
    | '/api/public/setup-db'
    | '/feed'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cadastro'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/chat'
    | '/_authenticated/cliente'
    | '/_authenticated/dashboard'
    | '/_authenticated/feed'
    | '/_authenticated/lojista'
    | '/_authenticated/parceiro'
    | '/_authenticated/prestador'
    | '/_authenticated/profile'
    | '/dashboard/lojista'
    | '/dashboard/prestador'
    | '/lojista/$id'
    | '/perfil/lojista'
    | '/auth/'
    | '/_authenticated/chat/$peerId'
    | '/_authenticated/feed/cliente'
    | '/_authenticated/feed/lojista'
    | '/_authenticated/feed/parceiro'
    | '/_authenticated/feed/prestador'
    | '/api/public/setup-db'
    | '/_authenticated/feed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  TermsRoute: typeof TermsRoute
  DashboardLojistaRoute: typeof DashboardLojistaRoute
  DashboardPrestadorRoute: typeof DashboardPrestadorRoute
  LojistaIdRoute: typeof LojistaIdRoute
  PerfilLojistaRoute: typeof PerfilLojistaRoute
  ApiPublicSetupDbRoute: typeof ApiPublicSetupDbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/perfil/lojista': {
      id: '/perfil/lojista'
      path: '/perfil/lojista'
      fullPath: '/perfil/lojista'
      preLoaderRoute: typeof PerfilLojistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojista/$id': {
      id: '/lojista/$id'
      path: '/lojista/$id'
      fullPath: '/lojista/$id'
      preLoaderRoute: typeof LojistaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/prestador': {
      id: '/dashboard/prestador'
      path: '/dashboard/prestador'
      fullPath: '/dashboard/prestador'
      preLoaderRoute: typeof DashboardPrestadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/lojista': {
      id: '/dashboard/lojista'
      path: '/dashboard/lojista'
      fullPath: '/dashboard/lojista'
      preLoaderRoute: typeof DashboardLojistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prestador': {
      id: '/_authenticated/prestador'
      path: '/prestador'
      fullPath: '/prestador'
      preLoaderRoute: typeof AuthenticatedPrestadorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parceiro': {
      id: '/_authenticated/parceiro'
      path: '/parceiro'
      fullPath: '/parceiro'
      preLoaderRoute: typeof AuthenticatedParceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lojista': {
      id: '/_authenticated/lojista'
      path: '/lojista'
      fullPath: '/lojista'
      preLoaderRoute: typeof AuthenticatedLojistaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cliente': {
      id: '/_authenticated/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof AuthenticatedClienteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed/': {
      id: '/_authenticated/feed/'
      path: '/'
      fullPath: '/feed/'
      preLoaderRoute: typeof AuthenticatedFeedIndexRouteImport
      parentRoute: typeof AuthenticatedFeedRoute
    }
    '/api/public/setup-db': {
      id: '/api/public/setup-db'
      path: '/api/public/setup-db'
      fullPath: '/api/public/setup-db'
      preLoaderRoute: typeof ApiPublicSetupDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/feed/prestador': {
      id: '/_authenticated/feed/prestador'
      path: '/prestador'
      fullPath: '/feed/prestador'
      preLoaderRoute: typeof AuthenticatedFeedPrestadorRouteImport
      parentRoute: typeof AuthenticatedFeedRoute
    }
    '/_authenticated/feed/parceiro': {
      id: '/_authenticated/feed/parceiro'
      path: '/parceiro'
      fullPath: '/feed/parceiro'
      preLoaderRoute: typeof AuthenticatedFeedParceiroRouteImport
      parentRoute: typeof AuthenticatedFeedRoute
    }
    '/_authenticated/feed/lojista': {
      id: '/_authenticated/feed/lojista'
      path: '/lojista'
      fullPath: '/feed/lojista'
      preLoaderRoute: typeof AuthenticatedFeedLojistaRouteImport
      parentRoute: typeof AuthenticatedFeedRoute
    }
    '/_authenticated/feed/cliente': {
      id: '/_authenticated/feed/cliente'
      path: '/cliente'
      fullPath: '/feed/cliente'
      preLoaderRoute: typeof AuthenticatedFeedClienteRouteImport
      parentRoute: typeof AuthenticatedFeedRoute
    }
    '/_authenticated/chat/$peerId': {
      id: '/_authenticated/chat/$peerId'
      path: '/$peerId'
      fullPath: '/chat/$peerId'
      preLoaderRoute: typeof AuthenticatedChatPeerIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatPeerIdRoute: typeof AuthenticatedChatPeerIdRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatPeerIdRoute: AuthenticatedChatPeerIdRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedFeedRouteChildren {
  AuthenticatedFeedClienteRoute: typeof AuthenticatedFeedClienteRoute
  AuthenticatedFeedLojistaRoute: typeof AuthenticatedFeedLojistaRoute
  AuthenticatedFeedParceiroRoute: typeof AuthenticatedFeedParceiroRoute
  AuthenticatedFeedPrestadorRoute: typeof AuthenticatedFeedPrestadorRoute
  AuthenticatedFeedIndexRoute: typeof AuthenticatedFeedIndexRoute
}

const AuthenticatedFeedRouteChildren: AuthenticatedFeedRouteChildren = {
  AuthenticatedFeedClienteRoute: AuthenticatedFeedClienteRoute,
  AuthenticatedFeedLojistaRoute: AuthenticatedFeedLojistaRoute,
  AuthenticatedFeedParceiroRoute: AuthenticatedFeedParceiroRoute,
  AuthenticatedFeedPrestadorRoute: AuthenticatedFeedPrestadorRoute,
  AuthenticatedFeedIndexRoute: AuthenticatedFeedIndexRoute,
}

const AuthenticatedFeedRouteWithChildren =
  AuthenticatedFeedRoute._addFileChildren(AuthenticatedFeedRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedClienteRoute: typeof AuthenticatedClienteRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRouteWithChildren
  AuthenticatedLojistaRoute: typeof AuthenticatedLojistaRoute
  AuthenticatedParceiroRoute: typeof AuthenticatedParceiroRoute
  AuthenticatedPrestadorRoute: typeof AuthenticatedPrestadorRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedClienteRoute: AuthenticatedClienteRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRouteWithChildren,
  AuthenticatedLojistaRoute: AuthenticatedLojistaRoute,
  AuthenticatedParceiroRoute: AuthenticatedParceiroRoute,
  AuthenticatedPrestadorRoute: AuthenticatedPrestadorRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CadastroRoute: CadastroRoute,
  TermsRoute: TermsRoute,
  DashboardLojistaRoute: DashboardLojistaRoute,
  DashboardPrestadorRoute: DashboardPrestadorRoute,
  LojistaIdRoute: LojistaIdRoute,
  PerfilLojistaRoute: PerfilLojistaRoute,
  ApiPublicSetupDbRoute: ApiPublicSetupDbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
